; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = examples/demo/LilyGoGui
;src_dir = examples/peripheral/RTC_AlarmByUnits
;src_dir = examples/lvgl/widgets/menu
default_envs = twatch-s3
boards_dir = ./board/LilyGoWatch-S3

[env]
lib_extra_dirs = .
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = spiffs
board_build.partitions = default_16MB.csv

[env:twatch-s3]
platform = espressif32@6.3.0
framework = arduino
board = LilyGoWatch-S3
extra_scripts = pre:fix_ble_libs.py
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1	
	-DBOARD_HAS_PSRAM
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-Wnarrowing
	-include extras/Setup212_LilyGo_T_Watch_S3.h
	-DUSER_SETUP_LOADED
lib_deps = 
	earlephilhower/ESP8266Audio @ 1.9.7
	crankyoldgit/IRremoteESP8266 @ 2.8.4
	jgromes/RadioLib @ 6.3.0
	bodmer/TFT_eSPI @ 2.5.30
	lvgl/lvgl @ 8.3.9
	kosme/arduinoFFT @ 1.6
	lewisxhe/XPowersLib @ 0.2.1
	lewisxhe/SensorLib @ 0.1.4
	t-vk/ESP32 BLE Mouse@^0.3.1
	t-vk/ESP32 BLE Keyboard@^0.3.2
	h2zero/NimBLE-Arduino@^1.3.8
